server:
  port: 8080
  servlet:
    contextPath: /pos-poc

spring:
  application:
    name: pos-poc
  datasource:
    url: jdbc:h2:mem:zooplusdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  profiles:
    active: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
  h2:
    console:
      enabled: true
